routes:
  '/*':
    headers:
      Access-Control-Allow-Origin: '*'
      Access-Control-Allow-Methods: 'GET, POST, PUT, DELETE, OPTIONS'
      Access-Control-Allow-Headers: 'Origin, Content-Type, Accept, Authorization, X-Request-With'
      Access-Control-Allow-Credentials: true
