routes:
  '/*':
    headers:
      Access-Control-Allow-Origin: 'requestersandbox.mturk.com'
      Access-Control-Allow-Methods: 'GET'
      Access-Control-Allow-Headers: 'Origin, Content-Type, Accept, Authorization, X-Request-With'
      Access-Control-Allow-Credentials: true
